version: '3.3'
services:
  caloriecounting-db: # Service Hosting MariaDb
    build: ./Database
    image: caloriecounting-database-image
    container_name: caloriecounting-db
    volumes:
      - caloriecounting-db:/var/lib/mysql
      - ./Database/:/CalorieCountingApp/
    restart: always 
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: CalorieCounting
      MYSQL_USER: root
    expose: 3306
    
  backend: # Backend C# Service
    build: ./BackEnd
    volumes:
      - ./BackEnd/:/CalorieCountingApp/
    image: caloriecounting-backend-image
    container_name: caloriecounting-backend
    restart: always
    depends_on: 
      - caloriecounting-db
    ports:
      - "5001:80"
volumes:
  caloriecounting-db: