version: '3.3'
services:
  caloriecounting-db: # Service Hosting MariaDb
    build: ./Database
    image: caloriecounting-database-image
    container_name: caloriecounting-db
    volumes:
      - ./.Volumes/caloriecounting-db/:/config/databases/
      - ./Database/:/CalorieCountingApp/
    restart: always 
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: CalorieCounting
      MYSQL_USER: root
    ports:
      - "7001:3306"
    
  backend: # Backend C# Service
    build: ./BackEnd
    volumes:
      - ./BackEnd/:/CalorieCountingApp/
    image: caloriecounting-backend-image
    container_name: caloriecounting-backend
    restart: always
    depends_on: 
      - caloriecounting-db
    links:
      - caloriecounting-db
    ports:
      - "5001:80"  

  frontend: # Frontend Vue Service
      build: ./calorie-counting
      volumes:
        - ./calorie-counting:/CalorieCountingApp/
      image: caloriecounting-frontend-image
      container_name: caloriecounting-frontend
      restart: always
      links:
        - backend
      depends_on: 
        - caloriecounting-db
        - backend
      ports:
        - "8001:80"