ARG VERSION=latest
FROM mariadb/server:${VERSION}
ENV MYSQL_ROOT_PASSWORD admin
ENV MYSQL_DATABASE: CalorieCounting
ENV MYSQL_USER: root
EXPOSE 3306


### Docker Build ###
# docker build --network=host -t caloriecounting-database-image ./Database

### Docker Run ###
# docker run -d \
# --network caloriecounting --network-alias database \
# --name=caloriecounting-database \
# -p 6001:3306 \
# -v caloriecounting-db:/var/lib/mysql \
# caloriecounting-database-image

### Connecting to mysql from host ###
# mysql -h localhost -P 6001 --protocol=tcp -u root -padmin
#docker run -d --network caloriecounting --network-alias database --name=caloriecounting-database -p 6001:3306 -v caloriecounting-db:/var/lib/mysql caloriecounting-database-image