CREATE TABLE FOOD (
    Id INTEGER AUTO_INCREMENT PRIMARY KEY,
    Name VARCHAR(255),
    CaloriesPerMetric DECIMAL,
    MetricId INTEGER
);

ALTER TABLE FOOD
ADD CONSTRAINT food_fk_metric
FOREIGN KEY (MetricId)
REFERENCES METRIC(Id);