CREATE TABLE INGREDIENT (
    Id INTEGER AUTO_INCREMENT PRIMARY KEY,
    Name VARCHAR(255),
    CaloriesPerMetric DECIMAL(10,5),
    MetricId INTEGER
);

ALTER TABLE INGREDIENT
ADD CONSTRAINT ingredient_fk_metric
FOREIGN KEY (MetricId)
REFERENCES METRIC(Id);