CREATE TABLE MEAL_INGREDIENT (
    Id INTEGER AUTO_INCREMENT PRIMARY KEY,
    MealId INTEGER NOT NULL,
    IngredientId INTEGER NOT NULL,
    MetricId INTEGER NOT NULL,
    Quantity DOUBLE NOT NULL
);

ALTER TABLE MEAL_INGREDIENT
ADD CONSTRAINT meal_ingredient_fk_meal
FOREIGN KEY (MealId)
REFERENCES MEAL(Id);

ALTER TABLE MEAL_INGREDIENT
ADD CONSTRAINT meal_ingredient_fk_ingredient
FOREIGN KEY (IngredientId)
REFERENCES INGREDIENT(Id);

ALTER TABLE MEAL_INGREDIENT
ADD CONSTRAINT meal_ingredient_fk_metric
FOREIGN KEY (MetricId)
REFERENCES METRIC(Id);