CREATE TABLE MEAL (
    Id INTEGER AUTO_INCREMENT PRIMARY KEY,
    Name VARCHAR(255) NOT NULL,
    UserId INTEGER NOT NULL,
    CookedWeight DOUBLE,
    CookedWeightMetricId INTEGER,
    RemainingWeight DOUBLE,
    CookedOn DATETIME NOT NULL
);

ALTER TABLE MEAL
ADD CONSTRAINT meal_fk_user
FOREIGN KEY (UserId)
REFERENCES USER(Id);

ALTER TABLE MEAL
ADD CONSTRAINT meal_fk_metric
FOREIGN KEY (CookedWeightMetricId)
REFERENCES METRIC(Id);