CREATE TABLE MEAL_COMPONENT (
    Id INTEGER AUTO_INCREMENT PRIMARY KEY,
    MealId INTEGER NOT NULL,
    FoodId INTEGER NOT NULL,
    MetricId INTEGER NOT NULL,
    Quantity DOUBLE NOT NULL
);

ALTER TABLE MEAL_COMPONENT
ADD CONSTRAINT meal_component_fk_meal
FOREIGN KEY (MealId)
REFERENCES MEAL(Id);

ALTER TABLE MEAL_COMPONENT
ADD CONSTRAINT meal_component_fk_food
FOREIGN KEY (FoodId)
REFERENCES FOOD(Id);

ALTER TABLE MEAL_COMPONENT
ADD CONSTRAINT meal_component_fk_metric
FOREIGN KEY (MetricId)
REFERENCES METRIC(Id);