CREATE TABLE TRACKING (
    Id INTEGER AUTO_INCREMENT PRIMARY KEY,
    UserId INTEGER,
    FoodId INTEGER,
    MetricId INTEGER,
    Quantity DOUBLE,
    `DateTime` DATETIME
);

ALTER TABLE TRACKING
ADD CONSTRAINT tracking_fk_user
FOREIGN KEY (UserId)
REFERENCES USER(Id);

ALTER TABLE TRACKING
ADD CONSTRAINT tracking_fk_food
FOREIGN KEY (FoodId)
REFERENCES FOOD(Id);

ALTER TABLE TRACKING
ADD CONSTRAINT tracking_fk_metric
FOREIGN KEY (MetricId)
REFERENCES METRIC(Id);
