CREATE TABLE TRACKING (
    Id INTEGER AUTO_INCREMENT PRIMARY KEY,
    UserId INTEGER NOT NULL,
    TrackingTypeId INTEGER NOT NULL,
    Quantity DOUBLE NOT NULL,
    Calories DOUBLE NOT NULL,
    `DateTime` DATETIME NOT NULL
);

ALTER TABLE TRACKING
ADD CONSTRAINT tracking_fk_user
FOREIGN KEY (UserId)
REFERENCES USER(Id);

ALTER TABLE TRACKING
ADD CONSTRAINT tracking_fk_tracking_type
FOREIGN KEY (TrackingTypeId)
REFERENCES TRACKING_TYPE(Id);