# FROM node:lts-alpine as build-stage
# WORKDIR /app
# COPY package*.json ./
# RUN npm install
# COPY . .
# RUN npm run build

FROM nginx:stable-alpine as production-stage
WORKDIR /app
COPY ./dist /usr/share/nginx/html
#COPY --from=build-stage /app/dist /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]

### Docker Build ###
# docker build --network=host -t caloriecounting-frontend-image .

### Docker Run ###
# docker run -it \
# -v ${PWD}:/caloriecounting-frontend \
# -v /caloriecounting/node_modules \
# -p 7001:3000 \
# -e CHOKIDAR_USEPOLLING=true \
# --name=caloriecounting-frontend \
# caloriecounting-frontend-image
